name: herpeton
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - anyio=4.10.0
  - aom=3.12.1
  - appnope=0.1.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - datasets=3.3.2
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - icu=73.1
  - imageio=2.37.2
  - ipykernel=6.31.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jansson=2.14
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.12.1
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.16.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.67.1
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libunistring=1.3
  - libuv=1.48.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mistune=3.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multiprocess=0.70.15
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numexpr=2.14.1
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.2.0
  - overrides=7.7.0
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycares=4.10.0
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.2.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qtconsole=5.7.0
  - qtpy=2.4.3
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.37.0
  - regex=2025.9.1
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.28.0
  - safetensors=0.6.2
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=80.9.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.51.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tokenizers=0.21.0
  - torchvision=0.17.2
  - tornado=6.5.1
  - traitlets=5.14.3
  - transformers=4.49.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvloop=0.22.1
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.0
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - arbor-process==0.1.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - braceexpand==0.1.7
      - contourpy==1.2.1
      - cramjam==2.8.3
      - cycler==0.12.1
      - dotenv==0.9.9
      - fastparquet==2024.5.0
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - idna==3.7
      - importlib-resources==6.4.0
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - multidict==6.0.5
      - numpy==1.26.4
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.3.0
      - polars-runtime-32==1.35.2
      - pyarrow==16.1.0
      - pyparsing==3.1.2
      - python-dotenv==1.2.1
      - pytz==2024.1
      - six==1.16.0
      - tqdm==4.66.4
      - tzdata==2024.1
      - webdataset==1.0.2
      - yarl==1.9.4
      - zipp==3.19.2
